### ISSUE TITLE
Clicking on a Failed Job throws an exception

### ISSUE THREAD

**Issue by Tolpan** [peh/jesque-admin#6]
In the List of Failed Jobs: 

![image](https://cloud.githubusercontent.com/assets/3987224/20108317/ec812d64-a5db-11e6-9a4c-d27b5be598a0.png)

When I click on a job, I don't see the details, but the "Message Column" vanishes and the console says:
"Uncaught TypeError: Cannot read property 'stackTrace' of null"

**Comment by bp-FLN** [comment]
this has been fixed
